### PR TITLE
Compiled the stream library.

### PR DESCRIPTION
**Pull request by milkovsky**

### CODE REVIEW

**Comment by fago** [comment]
Looks good to me!

**Comment by goldquest** [comment]
I think, we should only add a compiled stream library, either to releases, or to the master branch.

**Comment by milkovsky** [comment]
Not sure what is the best way here, as Drupal workflow for modules does not assume having release branches but release tags. See https://www.drupal.org/node/1068944 and https://www.drupal.org/node/1015226
E.g. we can compile it every time we make a new release tag. What do you think?

**Comment by goldquest** [comment]
Let's have all libraries always compiled in the master branch.

**Comment by goldquest** [comment]
Only on (or after) merging into the master, we compile everything.

**Pull request merged**
